#[START gae_python37_cloudsql_config]
runtime: python37

env_variables:
	CLOUD_SQL_USERNAME: root
	CLOUD_SQL_PASSWORD: 2I\G[iJJkG"4Ize}
	CLOUD_SQL_DATABASE_NAME: coincap
	CLOUD_SQL_CONNECTION_NAME: my-project-cc-371413:europe-west2:cc-group7
#[END gae_python37_cloudsql_config]